# ndfc_network_deleted_external_all/tasks/main.yml
---
- name: main REST GET fabrics
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics"
  register: mr1
  vars:
    ansible_connection: httpapi

- name: main set_fact active_fabrics 
  set_fact:
     active_fabrics: "{{ mr1.response.DATA | json_query(mq1) | to_json }}"
  vars:
    mq1: "[*].{FabricName: fabricName}"

- name: main deleted networks
  include_tasks: worker.yml
  loop: "{{ networks.values() | list }}"
