# ndfc_network_deleted_all/tasks/worker.yml
- name: worker deleted FABRIC {{ fabric_name }} NETWORK {{ item.net_name }} VRF {{ item.vrf_name }} VLAN {{ item.vlan_id }} SUBNET {{ item.gw_ip_subnet }}
  cisco.dcnm.dcnm_network:
    fabric: "{{ fabric_name }}"
    state: deleted
    config:
    - net_name: "{{ item.net_name }}"
