# ndfc_network_deleted_all/tasks/worker.yml
- ansible.builtin.include_role:
    name: ndfc_network_config_get
  vars:
    network_name: "{{ network.value.name }}"

- ansible.builtin.include_role:
    name: ndfc_fabric_config_get
  vars:
    fabric_name: "{{ network.value.fabric }}"

- name: worker deleted FABRIC {{ network.value.fabric }} NETWORK {{ network.value.net_name }} VRF {{ network.value.vrf_name }} VLAN {{ network.value.vlan_id }} SUBNET {{ network.value.gw_ip_subnet }}
  cisco.dcnm.dcnm_network:
    fabric: "{{ network.value.fabric }}"
    state: deleted
    config:
    - net_name: "{{ network.value.net_name }}"
  when: "network.value.fabric in active_fabrics"
  vars:
    ansible_connection: httpapi
