# ndfc_policy_vrf_rt_import_loop/tasks/policy_vrf_rt_import.yml
- name: worker {{ state }} FABRIC {{ fabric_name }} ITEM {{ item }} VRF_NAME {{ vrf_name }} import VRF.ASN:INDEX {{ import_vrf_name }}.{{ import_vrf_asn }}:{{ import_vrf_index }}
  cisco.dcnm.dcnm_policy:
    state: "{{ state }}"
    deploy: true
    fabric: "{{ fabric_name }}"
    config:
      - name: vrf_context_rt
        create_additional_policy: false
        policy_vars:
          VRF_NAME: "{{ vrf_name }}"
          ASN: "{{ import_vrf_asn }}"
          ALLOCATE_INDEX: "{{ import_vrf_index }}"
      - switch:
        - ip: "{{ devices[0].ip }}"
  vars:
    wq1: "[?fabric == '{{ fabric_name }}'] | [?vrf_name == '{{ import_vrf_name }}'].vrf_id | [0]"
    wq2: "[?name == '{{ fabric_name }}'].BGP_AS | [0]"
    wq3: "[?name == '{{ item }}'] | [?fabric == '{{ fabric_name }}']"
    import_vrf_index: "{{ vrfs | json_query(wq1) }}"
    import_vrf_asn: "{{ fabrics | json_query(wq2) }}"
    devices: "{{ leafs | json_query(wq3) + spines | json_query(wq3) + border_gateways | json_query(wq3) }}"
