# ndfc_rest_rediscover/tasks/main.yml
---
- name: main query FABRIC {{ fabric_name }} DEVICE {{ device_name }}
  include_tasks: worker.yml
  loop: "{{ r1 }}"
  vars:
    q1: "[?name == '{{ device_name }}'] | [?fabric == '{{ fabric_name }}']"
    r1: "{{ leafs | json_query(q1) + spines | json_query(q1) + border_gateways | json_query(q1) }}"
