# ndfc_device_info_get/tasks/worker.yml
- ansible.builtin.include_role:
    name: ndfc_device_config_get

- name: query FABRIC {{ device_config.switch_fabric }} NAME {{ device_config.name }} IP {{ device_config.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ device_config.switch_fabric }}"
    state: query
    config:
    - seed_ip: "{{ device_config.ip }}"
  register: wr1
  vars:
    ansible_connection: httpapi

- name: worker set_fact device_info
  set_fact:
    device_info: "{{ wr1.response | json_query(wq1) }}"
  vars:
    wq1: "[0]"
