# ndfc_device_info_get/tasks/worker.yml
- name: worker query FABRIC {{ d.fabric }} NAME {{ d.name }} IP {{ d.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ d.fabric }}"
    state: query
    config:
    - seed_ip: "{{ d.ip }}"
  register: wr1

- name: worker set_fact device_info
  set_fact:
    device_info: "{{ wr1.response | json_query(wq1) }}"
  vars:
    wq1: "[0]"
