# example_ndfc_rest_fabric_delete_f2.yml
---
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_network_deleted_all
  vars:
    fabric_name: MSD

- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_vrf_all
  vars:
    fabric_name: MSD
    state: deleted

- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_msd_child_remove
  vars:
    msd_fabric: MSD
    child_fabric: f1

- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_msd_child_remove
  vars:
    msd_fabric: MSD
    child_fabric: f2

- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_deleted_all
  vars:
    fabric_name: f1

- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_deleted_all
  vars:
    fabric_name: f2

- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_delete
  vars:
    fabric_name: MSD

- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_delete
  vars:
    fabric_name: f1

- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_delete
  vars:
    fabric_name: f2
