# example_ndfc_rest_fabric_switch_create_f1.yml
# This creates a standalone fabric (i.e. not MSD child).  As such, it provisions only the leaf and spine layers (does not provision border-gateways)
---
# Fabric and devices
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_switch_create
  vars:
    fabric_name: f1

# leaf_1
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_merged
  vars:
    device_name: leaf_1

# leaf_2
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_merged
  vars:
    device_name: leaf_2

# leaf_3
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_merged
  vars:
    device_name: leaf_3

# leaf_4
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_merged
  vars:
    device_name: leaf_4

# spine_1
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_merged
  vars:
    device_name: spine_1

# spine_2
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_merged
  vars:
    device_name: spine_2

# vpc_1
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_rest_vpc_create
  vars:
    vpc_name: vpc_1

- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_vpc_interface_merged_all
  vars:
    vpc_name: vpc_1

# vpc_2
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_rest_vpc_create
  vars:
    vpc_name: vpc_2

- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_vpc_interface_merged_all
  vars:
    vpc_name: vpc_2

# VRFs
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_vrf_all
  vars:
    fabric_name: f1
    state: replaced

# Networks
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_network_replaced_all
  vars:
    fabric_name: f1

# Deploy
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: f1

- hosts: ndfc
  name: fabric f1 vrf {{ vrf_name }} import vrf {{ import_vrf_name }} route-targets
  gather_facts: false
  vars:
    state: merged
    vrf_name: v1
    import_vrf_name: v2
    devices:
      - leaf_1
      - leaf_2
      - leaf_3
      - leaf_4
  roles:
    - ndfc_policy_vrf_rt_import_evpn_loop

# Deploy
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: f1

- hosts: ndfc
  name: fabric f1 vrf {{ vrf_name }} import vrf {{ import_vrf_name }} route-targets
  gather_facts: false
  vars:
    state: merged
    vrf_name: v2
    import_vrf_name: v1
    devices:
      - leaf_1
      - leaf_2
      - leaf_3
      - leaf_4
  roles:
    - ndfc_policy_vrf_rt_import_evpn_loop

# Deploy
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: f1
