# example_ndfc_vrf_query.yml
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_vrf_query
  vars:
    vrf_name: msd_v1
  tasks:
  - debug:
      msg: "vrf_info.parent.fabric: {{ vrf_info.parent.fabric }}"
  - debug:
      msg: "vrf_info.parent.vrfId: {{ vrf_info.parent.vrfId }}"
  - debug:
      msg: "vrf_info.parent.vrfStatus: {{ vrf_info.parent.vrfStatus }}"
