# example_ndfc_rest_fabric_create_msd_with_children_vpc.yml
# Create the following
#   - 2x VXLAN/EVPN fabrics (EasyFabric)
#     - 2x VPC Pairs (4x leaf)
#     - 2x spine
#     - 2x border_gateway
#   - 1x MSD fabric
#   - DCI network features back-to-back border_gateway
---
# Fabric f1

# Fabric f1 - Create
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_create_easy_fabric
  vars:
    fabric_name: f1

# Fabric f1 - Get list of devices from Ansible inventory
-   hosts: ndfc
    gather_facts: false
    roles:
    - ndfc_device_list_get
    vars:
        fabric_name: f1

# Fabric f1 - Add devices
-   hosts: ndfc
    gather_facts: false
    roles:
    - ndfc_device_list_merged
    vars:
        devices: "{{ device_list }}"
        fabric_name: f1

# Fabric f2

# Fabric f2 - Create
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_create_easy_fabric
  vars:
    fabric_name: f2

# Fabric f2 - Get list of devices from Ansible inventory
-   hosts: ndfc
    gather_facts: false
    roles:
    - ndfc_device_list_get
    vars:
        fabric_name: f2

# Fabric f2 - Add devices
-   hosts: ndfc
    gather_facts: false
    roles:
    - ndfc_device_list_merged
    vars:
        devices: "{{ device_list }}"
        fabric_name: f2

# Fabric MSD
# Fabric MSD Create
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_create_msd
  vars:
    msd_fabric: MSD

# Fabric f1 - Create vpc_1
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_rest_vpc_create
  vars:
    vpc_name: vpc_1
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: f1

# Fabric f1 - Add vpc_1 interfaces
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_vpc_interface_merged_all
  vars:
    vpc_name: vpc_1
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: f1

# Fabric f1 - Create vpc_2
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_rest_vpc_create
  vars:
    vpc_name: vpc_2
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: f1

# Fabric f1 - Add vpc_2 interfaces
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_vpc_interface_merged_all
  vars:
    vpc_name: vpc_2
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: f1

# Fabric f2 - Create vpc_3
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_rest_vpc_create
  vars:
    vpc_name: vpc_3
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: f2

# Fabric f2 - Add vpc_3 interfaces
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_vpc_interface_merged_all
  vars:
    vpc_name: vpc_3
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: f2

# Fabric f2 - Create vpc_4
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_rest_vpc_create
  vars:
    vpc_name: vpc_4
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: f2

# Fabric f2 - Add vpc_4 interfaces
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_vpc_interface_merged_all
  vars:
    vpc_name: vpc_4
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: f2


# Fabric MSD - Add child_fabric f1
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_msd_child_add
  vars:
    msd_fabric: MSD
    child_fabric: f1
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: MSD

# Fabric MSD - Add child_fabric f2
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_msd_child_add
  vars:
    msd_fabric: MSD
    child_fabric: f2
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: MSD


# Fabric MSD - Add VRFs.  These will be inherited by the child fabrics.
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_vrf_all
  vars:
    fabric_name: MSD
    state: merged
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: MSD

# Fabric MSD - Add networks.  These will be inherited by the child fabrics.
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_network_replaced_all
  vars:
    fabric_name: MSD
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy_all
  vars:
    fabric_name: MSD
