# example_ndfc_rest_fabric_access_mode_get.yml
# NOTE:
# ndfc_rest_fabric_access_mode_get is not intended for use
# within playbooks (rather, it is used within other roles).
#
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_access_mode_get
  vars:
    fabric_name: f1
  tasks:
  - block:
    - debug:
        msg: "fabric {{ fabric_name }} read_only: {{ read_only }}"
