# example_ndfc_device_list_by_fabric_rest.yml
#
# Query fabric fabric_name for list of switch information and print
# specific items (model number and ip address) from each switch dictionary
#
# The Role ndfc_device_list_by_fabric_rest returns JSON object 'info' 
# which contains a list of switch dictionaries
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_list_by_fabric_rest
  vars:
    fabric_name: f2
  tasks:
      - debug:
          msg: "item.model: {{ item }}"
        loop: "{{ info | json_query(q1) }}"
        vars:
          q1: "[*].model"
      - debug:
          msg: "item.ipAddress: {{ item }}"
        loop: "{{ info | json_query(q2) }}"
        vars:
          q2: "[*].ipAddress"
