# example_ndfc_device_list_merged.yml
---
-   hosts: ndfc
    gather_facts: false
    roles:
    - ndfc_device_list_get
    vars:
        fabric_name: f1
-   hosts: ndfc
    gather_facts: false
    roles:
    - ndfc_device_list_merged
    vars:
        fabric_name: f1
        devices: "{{ device_list }}"
