# example_ndfc_device_list_by_fabric_rest.yml
#
# Query fabric fabric_name for list of switch dictionaries and print
# specific items from each switch dictionary.
#
# The Role ndfc_device_list_by_fabric_rest returns JSON object 'info' 
# which contains a list of switch dictionaries
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_list_by_fabric_rest
  vars:
    fabric_name: f2
  tasks:
      - debug:
          msg: "ipAddress: {{ item.ipAddress }} logicalName: {{ item.logicalName }} model {{ item.model }} release {{ item.release }}"
        loop: "{{ info | json_query(q1) }}"
        vars:
          q1: "[*].{ ipAddress: ipAddress, model: model, release: release, logicalName: logicalName }"
        loop_control:
          label: device_info
