# example_ndfc_rest_config_deploy.yml
# Calls config-save on the device's fabric, and config_deploy on device_name
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_config_deploy
  vars:
    device_name: leaf_1
