# example_ndfc_device_ipv4_address_local_get.yml
# Query device entry in inventory/group_vars/ndfc/01_devices.yml 
# containing fabric_name and device_name, and print the device's
# ipv4 address.
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_ipv4_address_local_get
  vars:
    device_name: leaf_1
  tasks:
  - block:
    - debug:
        msg: "device_ipv4_address: {{ device_ipv4_address }}"
    when: "device_ipv4_address != ''"
