# example_ndfc_device_ipv4_address_local_get.yml
# Query device entry in ndfc_common with fabric_name and device_name
# and print the switch's ipv4 address based on the vars config in ndfc_common
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_ipv4_address_local_get
  vars:
    fabric_name: f2
    device_name: leaf_1
  tasks:
  - block:
    - debug:
        msg: "device_ipv4_address: {{ device_ipv4_address }}"
    when: "device_ipv4_address != ''"
