# example_ndfc_vrf_query.yml
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_vrf_query
  vars:
    fabric_name: f1
    vrf_name: v1
  tasks:
  - block:
    - debug:
        msg: "info.parent.fabric: {{ info.parent.fabric }}"
    - debug:
        msg: "info.parent.vrfId: {{ info.parent.vrfId }}"
    - debug:
        msg: "info.parent.vrfStatus: {{ info.parent.vrfStatus }}"
