# example_ndfc_rest_fabric_msd_add.yml
# Adds add_fabric (f1 and f2) as a children of msd_fabric (MSD)
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_msd_add
  vars:
    msd_fabric: MSD
    add_fabric: f1

- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_msd_add
  vars:
    msd_fabric: MSD
    add_fabric: f2
