# example_ndfc_rest_fabric_delete_f1.yml
---
- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_network_deleted_all
  vars:
    fabric_name: f1

- hosts: ndfc
  gather_facts: false
  roles:
  - ndfc_vrf_all
  vars:
    fabric_name: f1
    state: deleted

- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_deleted_all
  vars:
    fabric_name: f1

- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_delete
  vars:
    fabric_name: f1
