---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_network_info_get
  vars:
    network_name: msd_n1111
  tasks:
  - block:
    - debug:
        var: network_info | default('unable to find network. Check network_name.', true)
