# example_ndfc_device_merged.yml
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_merged
  vars:
    fabric_name: f1
    device_name: spine_1
    # Default is true. See README for ndfc_device_merged Role
    config_deploy_for_existing_device: true
