# example_ndfc_rest_fabric_active_fabrics_get.yml
# Query NDFC for the list of active fabrics and print the list
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_rest_fabric_active_fabrics_get
  tasks:
  - block:
    - debug:
        var: active_fabrics
    when: "active_fabrics != ''"
