# example_ndfc_network_config_get.yml
# Print configuration of network from vars defined in
# inventory/group_vars/ndfc/03_networks.yml
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_network_config_get
  vars:
    network_name: f1_n1111
  tasks:
  - block:
    - debug:
        var: network_config
