# example_ndfc_device_info_get.yml
# Query NX-OS switch associated with fabric_name + device_name
# Returns device_info JSON object (see ndfc_device_info_get/README.md for object format)
---
- hosts: ndfc
  gather_facts: false
  roles:
    - ndfc_device_info_get
  vars:
    fabric_name: f2
    device_name: leaf_1
  tasks:
  - block:
    - debug:
        msg: "logicalName: {{ device_info.logicalName }}"
    - debug:
        msg: "uptime: {{ device_info.upTimeStr }}"
    - debug:
        msg: "serial: {{ device_info.serialNumber }}"
    - debug:
        msg: "version: {{ device_info.release }}"
    - debug:
        msg: "switchDbId: {{ device_info.switchDbID }}"
