# ndfc_network_deleted_msd_all/tasks/worker.yml
- ansible.builtin.include_role:
    name: ndfc_fabric_config_get
  vars:
    ansible_connection: local
    fabric_name: "{{ item.fabric }}"

- name: worker deleted FABRIC {{ item.fabric }} NETWORK {{ item.net_name }} VRF {{ item.vrf_name }} VLAN {{ item.vlan_id }} SUBNET {{ item.gw_ip_subnet }}
  cisco.dcnm.dcnm_network:
    fabric: "{{ item.fabric }}"
    state: deleted
    config:
    - net_name: "{{ item.net_name }}"
  when: "item.fabric in active_fabrics and fabric_config.type == 'msd'"
  vars:
    ansible_connection: httpapi
