# ndfc_network_replaced_all/tasks/main.yml
---
- name: main replaced Network FABRIC {{ fabric_name }}
  include_tasks: worker.yml
  loop: "{{ networks | json_query(mq1) }}"
  vars:
    mq1: "[?fabric == '{{ fabric_name }}']"
