# ndfc_network_replaced_all/tasks/worker.yml
- name: worker replaced FABRIC {{ network.value.fabric }} NETWORK {{ network.value.net_name }} VRF {{ network.value.vrf_name }} VLAN {{ network.value.vlan_id }} SUBNET {{ network.value.gw_ip_subnet }}"
  cisco.dcnm.dcnm_network:
    fabric: "{{ fabric_name }}"
    state: replaced
    config:
    - net_name: "{{ network.value.net_name }}"
      vrf_name: "{{ network.value.vrf_name }}"
      vlan_id: "{{ network.value.vlan_id }}"
      gw_ip_subnet: "{{ network.value.gw_ip_subnet }}"
      attach: "{{ network.value.attach }}"
  vars:
    ansible_connection: httpapi
