# ndfc_rest_fabric_get_access_mode
# Returns the current fabric access mode in var 'read_only'
# if fabric exists, read_only will be either true or false
# if fabric does not exist, read_only will be null
---
- ansible.builtin.include_role:
    name: ndfc_rest_fabric_active_fabrics_get

- name: get fabric access_mode fabric {{ fabric_name }} active_fabrics {{ active_fabrics }}
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/accessmode"
  register: mr2
  when: fabric_name in active_fabrics

- name: "main set_fact read_only {{ mr2.response.DATA.readonly }} if fabric exists"
  set_fact:
    read_only: "{{ mr2.response.DATA.readonly }}"
  when: fabric_name in active_fabrics

- name: main set_fact read_only null if fabric does not exist)
  set_fact:
    read_only: null
  when: fabric_name not in active_fabrics
