# ndfc_vpc_interface_merged_all/tasks/main.yml
- name: main merged VPC {{ vpc_name }} vpc_interface
  include_tasks: worker.yml
  loop: "{{ vpc_interfaces.values() | list | json_query(mq1) }}"
  vars:
    mq1: "[?vpc_name == '{{ vpc_name }}']"
