# ndfc_vpc_interface_merged_all/tasks/worker.yml
# - Retrieve serialNumber and isVpcConfigured for both target vpc peers
# - if, for both peers, serialNumber != '' and isVpcConfigured == 'false'
#     create the peers
# - else
#     skip

# set_fact for p1_serial, p1_vpc, p1_db_id
- name: worker query {{ item.fabric }} {{ item.vpc_name }} vpc_peer_1 {{ ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: query
    config:
    - seed_ip: "{{ ip }}"
  register: p1_result
  vars:
    q1: "[?fabric == '{{ item.fabric }}'] | [?vpc_name == '{{ item.vpc_name }}'].peer_1_ip | [0]"
    ip: "{{ vpc_peers | json_query(q1)}}"
- name: worker set_fact {{ item.fabric }} {{ item.vpc_name }} {{ item.vpc_port_id }} - p1_serial, p1_vpc, p1_db_id, p1_ip
  set_fact:
    p1_serial: "{{ p1_result.response | json_query(q2) }}"
    p1_vpc: "{{ p1_result.response | json_query(q3) }}"
    p1_db_id: "{{ p1_result.response | json_query(q4) }}"
    p1_ip: "{{ p1_result.response | json_query(q5) }}"
  vars:
    q2: "[0].serialNumber"
    q3: "[0].isVpcConfigured"
    q4: "[0].switchDbID"
    q5: "[0].ipAddress"

# set_fact for p2_serial, p2_vpc, p2_db_id
- name: worker query {{ item.fabric }} {{ item.vpc_name }} vpc_peer_2 {{ ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: query
    config:
    - seed_ip: "{{ ip }}"
  register: p2_result
  vars:
    q6: "[?fabric == '{{ item.fabric }}'] | [?vpc_name == '{{ item.vpc_name }}'].peer_2_ip | [0]"
    ip: "{{ vpc_peers | json_query(q6)}}"

- name: worker set_fact {{ item.fabric }} {{ item.vpc_name }} {{ item.vpc_port_id }} - p2_serial, p2_vpc, p2_db_id, p2_ip
  set_fact:
    p2_serial: "{{ p2_result.response | json_query(q7) }}"
    p2_vpc: "{{ p2_result.response | json_query(q8) }}"
    p2_db_id: "{{ p2_result.response | json_query(q9) }}"
    p2_ip: "{{ p2_result.response | json_query(q10) }}"
  vars:
    q7: "[0].serialNumber"
    q8: "[0].isVpcConfigured"
    q9: "[0].switchDbID"
    q10: "[0].ipAddress"

- name: worker merged {{ item.fabric }} {{ item.vpc_name }} {{ item.vpc_port_id }} {{ item.interface_mode }} {{ p1_ip }}/{{p2_ip}}
  cisco.dcnm.dcnm_interface:
    fabric: "{{ item.fabric }}"
    state: merged
    config:
      - name: "{{ item.vpc_port_id }}"
        type: vpc
        switch:
          - "{{ p1_ip }}"
          - "{{ p2_ip }}"
        deploy: true
        profile:
          admin_state: true
          mode: "{{ item.interface_mode }}"
          peer1_members: "{{ item.member_list }}"
          peer2_members: "{{ item.member_list }}"
          pc_mode: "{{ item.port_channel_mode }}"
          bpdu_guard: true
          port_type_fast: true
          mtu: jumbo
          peer1_allowed_vlans: all
          peer2_allowed_vlans: all
          peer1_description: "{{ item.vpc_port_id}} {{ item.interface_mode}}"
          peer2_description: "{{ item.vpc_port_id}} {{ item.interface_mode}}"
