---
# ndfc_device_deleted/tasks/worker.yml
- name: worker query FABRIC {{ item.fabric }} NAME {{ item.name }} IP {{ item.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ fabric_name }}"
    state: query
    config:
    - seed_ip: "{{ item.ip }}"
  register: result

- name: worker set_fact serial
  set_fact:
    serial: "{{ result.response | json_query(q2) }}"
  vars:
    q2: "[0].serialNumber"

- name: worker deleted FABRIC {{ item.fabric }} NAME {{ item.name }} IP {{ item.ip}} SERIAL ({{ serial }})
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: deleted
    config:
    - seed_ip: "{{ item.ip }}"
  when: "serial != ''"
