---
- ansible.builtin.include_role:
    name: ndfc_device_serial_number_get
  vars:
    device_name: "{{ item.name }}"
    fabric_name: "{{ item.fabric }}"

- name: worker deleted device_fabric {{ item.fabric }} device_name {{ item.name }} device_ip {{ item.ip}} device_serial_number ({{ device_serial_number }})
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: deleted
    config:
    - seed_ip: "{{ item.ip }}"
  when: "device_serial_number != ''"

- ansible.builtin.include_role:
    name: ndfc_rest_config_deploy_all
