---
# ndfc_device_deleted/tasks/worker.yml
- name: worker query FABRIC {{ item.fabric }} NAME {{ item.name }} IP {{ item.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ fabric_name }}"
    state: query
    config:
    - seed_ip: "{{ item.ip }}"
  register: wr1

- name: worker set_fact serial
  set_fact:
    serial: "{{ wr1.response | json_query(wq1) }}"
  vars:
    wq1: "[0].serialNumber"

- name: worker deleted FABRIC {{ item.fabric }} NAME {{ item.name }} IP {{ item.ip}} SERIAL ({{ serial }})
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: deleted
    config:
    - seed_ip: "{{ item.ip }}"
  when: "serial != ''"
