# ndfc_rest_fabric_msd_create/tasks/main.yml
---
- ansible.builtin.include_role:
    name: ndfc_rest_fabric_active_fabrics_get

- name: worker set_fact msd_fabric name {{ fabric_name }}
  set_fact:
     _config: "{{ msd_fabrics | json_query(mq2) }}"
  vars:
    mq2: "{{ msd_fabric }}"


- name: main REST POST msd_fabric {{ msd_fabric }} active_fabrics {{ active_fabrics }}
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/"
    json_data: "{{ vars_dict | to_json }}"
  when: "msd_fabric not in active_fabrics"
  vars:
    ansible_connection: httpapi
    vars_dict:
      fabricName: "{{ msd_fabric }}"
      templateName: "MSD_Fabric"
      nvPairs:
        FABRIC_NAME: "{{ msd_fabric }}"
        L2_SEGMENT_ID_RANGE: "{{ _config.L2_SEGMENT_ID_RANGE }}"
        L3_PARTITION_ID_RANGE: "{{ _config.L3_PARTITION_ID_RANGE }}"
        default_vrf: "Default_VRF_Universal"
        default_network: "Default_Network_Universal"
        vrf_extension_template: "Default_VRF_Extension_Universal"
        network_extension_template: "Default_Network_Extension_Universal"
        ANYCAST_GW_MAC: "{{ _config.ANYCAST_GW_MAC }}"
        MS_LOOPBACK_ID: "{{ _config.MS_LOOPBACK_ID }}"
        ENABLE_PVLAN: "{{ _config.ENABLE_PVLAN }}"
        TOR_AUTO_DEPLOY: false
        FABRIC_TYPE: MFD
        FF: MSD
        MSO_CONTROLER_ID: ""
        MSO_SITE_GROUP_NAME: ""
        PREMSO_PARENT_FABRIC: ""
        DCNM_ID: ""
        MS_IFC_BGP_PASSWORD_ENABLE_PREV: ""
        MS_IFC_BGP_AUTH_KEY_TYPE_PREV: ""
        MS_IFC_BGP_PASSWORD_PREV: ""
        BORDER_GWY_CONNECTIONS: "{{ _config.BORDER_GWY_CONNECTIONS }}"
        RP_SERVER_IP: ""
        BGP_RP_ASN: ""
        MS_UNDERLAY_AUTOCONFIG: "{{ _config.MS_UNDERLAY_AUTOCONFIG }}"
        DELAY_RESTORE: "{{ _config.DELAY_RESTORE }}"
        CLOUDSEC_AUTOCONFIG: false
        CLOUDSEC_KEY_STRING: ""
        CLOUDSEC_ALGORITHM: ""
        CLOUDSEC_ENFORCEMENT: ""
        CLOUDSEC_REPORT_TIMER: ""
        IS_READ_ONLY: "{{ IS_READ_ONLY }}"
        MS_IFC_BGP_PASSWORD_ENABLE: false
        MS_IFC_BGP_PASSWORD: ""
        MS_IFC_BGP_AUTH_KEY_TYPE: ""
        LOOPBACK100_IP_RANGE: "{{ _config.LOOPBACK100_IP_RANGE }}"
        DCI_SUBNET_RANGE: "{{ _config.DCI_SUBNET_RANGE }}"
        DCI_SUBNET_TARGET_MASK: "{{ _config.DCI_SUBNET_TARGET_MASK }}"
        enableScheduledBackup: ""
        scheduledTime: ""
