# ndfc_rest_fabric_msd_create/tasks/main.yml
---
- name: main REST GET fabrics
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics"
  register: result
- name: main set_fact active_fabrics
  set_fact:
     active_fabrics: "{{ result.response.DATA | json_query(query) | to_json }}"
  vars:
    query: "[*].{FabricName: fabricName}"
# TODO: add relevant user-configurable parameters to common_vars and update the
# below accordingly.
- name: main set_fact FABRIC {{ msd_fabric }}
  set_fact:
     L2_SEGMENT_ID_RANGE: "{{ msd_fabrics | json_query(q1) }}"
     L3_PARTITION_ID_RANGE: "{{ msd_fabrics | json_query(q2) }}"
     ANYCAST_GW_MAC: "{{ msd_fabrics | json_query(q3) }}"
     MS_LOOPBACK_ID: "{{ msd_fabrics | json_query(q4) }}"
     BORDER_GWY_CONNECTIONS: "{{ msd_fabrics | json_query(q5) }}"
     MS_UNDERLAY_AUTOCONFIG: "{{ msd_fabrics | json_query(q6) }}"
     DELAY_RESTORE: "{{ msd_fabrics | json_query(q7) }}"
     LOOPBACK100_IP_RANGE: "{{ msd_fabrics | json_query(q8) }}"
     DCI_SUBNET_RANGE: "{{ msd_fabrics | json_query(q9) }}"
     DCI_SUBNET_TARGET_MASK: "{{ msd_fabrics | json_query(q10) }}"
  vars:
    q1: "[?name == '{{ msd_fabric }}'].L2_SEGMENT_ID_RANGE | [0]"
    q2: "[?name == '{{ msd_fabric }}'].L3_PARTITION_ID_RANGE | [0]"
    q3: "[?name == '{{ msd_fabric }}'].ANYCAST_GW_MAC | [0]"
    q4: "[?name == '{{ msd_fabric }}'].MS_LOOPBACK_ID | [0]"
    q5: "[?name == '{{ msd_fabric }}'].BORDER_GWY_CONNECTIONS | [0]"
    q6: "[?name == '{{ msd_fabric }}'].MS_UNDERLAY_AUTOCONFIG | [0]"
    q7: "[?name == '{{ msd_fabric }}'].DELAY_RESTORE | [0]"
    q8: "[?name == '{{ msd_fabric }}'].LOOPBACK100_IP_RANGE | [0]"
    q9: "[?name == '{{ msd_fabric }}'].DCI_SUBNET_RANGE | [0]"
    q10: "[?name == '{{ msd_fabric }}'].DCI_SUBNET_TARGET_MASK | [0]"

- name: main REST POST MSD FABRIC {{ msd_fabric }} ACTIVE_FABRICS {{ active_fabrics }}
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/"
    json_data: "{{ vars_dict | to_json }}"
  when: "msd_fabric not in active_fabrics"
  vars:
    vars_dict:
      fabricName: "{{ msd_fabric }}"
      templateName: "MSD_Fabric"
      nvPairs:
        FABRIC_NAME: "{{ msd_fabric }}"
        L2_SEGMENT_ID_RANGE: "{{ L2_SEGMENT_ID_RANGE }}"
        L3_PARTITION_ID_RANGE: "{{ L3_PARTITION_ID_RANGE }}"
        default_vrf: "Default_VRF_Universal"
        default_network: "Default_Network_Universal"
        vrf_extension_template: "Default_VRF_Extension_Universal"
        network_extension_template: "Default_Network_Extension_Universal"
        ANYCAST_GW_MAC: "{{ ANYCAST_GW_MAC }}"
        MS_LOOPBACK_ID: "{{ MS_LOOPBACK_ID }}"
        TOR_AUTO_DEPLOY: false
        FABRIC_TYPE: MFD
        FF: MSD
        MSO_CONTROLER_ID: ""
        MSO_SITE_GROUP_NAME: ""
        PREMSO_PARENT_FABRIC: ""
        DCNM_ID: ""
        MS_IFC_BGP_PASSWORD_ENABLE_PREV: ""
        MS_IFC_BGP_AUTH_KEY_TYPE_PREV: ""
        MS_IFC_BGP_PASSWORD_PREV: ""
        BORDER_GWY_CONNECTIONS: "{{ BORDER_GWY_CONNECTIONS }}"
        RP_SERVER_IP: ""
        BGP_RP_ASN: ""
        MS_UNDERLAY_AUTOCONFIG: "{{ MS_UNDERLAY_AUTOCONFIG }}"
        DELAY_RESTORE: "{{ DELAY_RESTORE }}"
        CLOUDSEC_AUTOCONFIG: false
        CLOUDSEC_KEY_STRING: ""
        CLOUDSEC_ALGORITHM: ""
        CLOUDSEC_ENFORCEMENT: ""
        CLOUDSEC_REPORT_TIMER: ""
        MS_IFC_BGP_PASSWORD_ENABLE: false
        MS_IFC_BGP_PASSWORD: ""
        MS_IFC_BGP_AUTH_KEY_TYPE: ""
        LOOPBACK100_IP_RANGE: "{{ LOOPBACK100_IP_RANGE }}"
        DCI_SUBNET_RANGE: "{{ DCI_SUBNET_RANGE }}"
        DCI_SUBNET_TARGET_MASK: "{{ DCI_SUBNET_TARGET_MASK }}"
        enableScheduledBackup: ""
        scheduledTime: ""
