# ndfc_policy_vrf_rt_import_evpn/tasks/main.yml
---
- name: main {{ state }} FABRIC {{ fabric_name }} DEVICE {{ device_name }} vrf route-target evpn import
  include_tasks: worker.yml
  loop: "{{ mr1 }}"
  vars:
    mq1: "[?name == '{{ device_name }}'] | [?fabric == '{{ fabric_name }}']"
    mr1: "{{ leafs | json_query(mq1) + spines | json_query(mq1) + border_gateways | json_query(mq1) }}"
