# ndfc_rest_rediscover/tasks/main.yml
---
- name: main query FABRIC {{ fabric_name }} DEVICE {{ device_name }}
  include_tasks: worker.yml
  loop: "{{ mr1 }}"
  vars:
    mq1: "[?name == '{{ device_name }}'] | [?fabric == '{{ fabric_name }}']"
    mr1: "{{ leafs | json_query(mq1) + spines | json_query(mq1) + border_gateways | json_query(mq1) }}"
