# ndfc_rest_rediscover/tasks/worker.yml

- ansible.builtin.include_role:
    name: ndfc_device_config_get

- name: worker query FABRIC {{ device_config.switch_fabric }} ROLE {{ device_config.role }} NAME {{ device_config.name }} IP {{ device_config.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ device_config.switch_fabric }}"
    state: query
    config:
    - seed_ip: "{{ device_config.ip }}"
  register: wr1
  vars:
    ansible_connection: httpapi

- name: worker set_fact device_id FABRIC {{ device_config.switch_fabric }} ROLE {{ device_config.role }} NAME {{ device_config.name }} IP {{ device_config.ip }}
  set_fact:
     device_id: "{{ wr1.response | json_query(q2) | to_json }}"
  vars:
    q2: "[0].switchDbID"

- name: worker REST POST rediscoverSwitch FABRIC {{ device_config.switch_fabric }} ROLE {{ device_config.role }} NAME {{ device_config.name }} IP {{ device_config.ip }} DEVICE_ID {{ device_id }}
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-discovery/rediscoverSwitch"
    json_data: "{{ vars_list | to_json }}"
  when: "device_id != None"
  vars:
    ansible_connection: httpapi
    vars_list:
      - "{{ device_id }}"
