# ndfc_rest_rediscover/tasks/worker.yml
- name: worker query FABRIC {{ item.fabric }} ROLE {{ item.role }} NAME {{ item.name }} IP {{ item.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: query
    config:
    - seed_ip: "{{ item.ip }}"
  register: result

- name: worker set_fact device_id FABRIC {{ item.fabric }} ROLE {{ item.role }} NAME {{ item.name }} IP {{ item.ip }}
  set_fact:
     device_id: "{{ result.response | json_query(q2) | to_json }}"
  vars:
    q2: "[0].switchDbID"

- name: worker REST POST rediscoverSwitch FABRIC {{ item.fabric }} ROLE {{ item.role }} NAME {{ item.name }} IP {{ item.ip }} DEVICE_ID {{ device_id }}
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-discovery/rediscoverSwitch"
    json_data: "{{ vars_list | to_json }}"
  when: "device_id != None"
  vars:
    vars_list:
      - "{{ device_id }}"
