# ndfc_vrf_replaced/tasks/worker.yml
- name: worker replaced FABRIC {{ item.fabric }} VRF {{ item.vrf_name }} VRF_ID {{ item.vrf_id }} VLAN {{ item.vlan_id }}
  cisco.dcnm.dcnm_vrf:
    fabric: "{{ item.fabric }}"
    state: replaced
    config:
    - vrf_name: "{{ item.vrf_name }}"
      vrf_id: "{{ item.vrf_id }}"
      vlan_id: "{{ item.vlan_id }}"
      vrf_template: Default_VRF_Universal
      vrf_extension_template: Default_VRF_Extension_Universal
      service_vrf_template: null
      attach: "{{ item.attach }}"
