# vpc_config_get/tasks/main.yml
---
- name: set_fact vpc_config {{ vpc_name }}
  ansible.builtin.set_fact:
     vpc_config: "{{ vpc_peers | json_query(vpc_config_get_q1) }}"
  vars:
    vpc_config_get_q1: "{{ vpc_name }}"
