vrfs:
  f1_v1:
    name: f1_v1
    fabric: "{{ switch_fabrics.f1.name }}"
    vrf_name: v1
    vrf_id: 63031
    vlan_id: 3031
    vrf_template: Default_VRF_Universal
    vrf_extension_template: Default_VRF_Extension_Universal
    service_vrf_template: null
    attach:
    - ip_address: "{{ devices.leaf_1.ip }}"
    - ip_address: "{{ devices.leaf_2.ip }}"
    - ip_address: "{{ devices.leaf_3.ip }}"
    - ip_address: "{{ devices.leaf_4.ip }}"

  f1_v2:
    name: f1_v2
    fabric: "{{ switch_fabrics.f1.name }}"
    vrf_name: v2
    vrf_id: 63032
    vlan_id: 3032
    vrf_template: Default_VRF_Universal
    vrf_extension_template: Default_VRF_Extension_Universal
    service_vrf_template: null
    attach:
    - ip_address: "{{ devices.leaf_1.ip }}"
    - ip_address: "{{ devices.leaf_2.ip }}"
    - ip_address: "{{ devices.leaf_3.ip }}"
    - ip_address: "{{ devices.leaf_4.ip }}"

  f2_v1:
    name: f2_v1
    fabric: "{{ switch_fabrics.f2.name }}"
    vrf_name: v1
    vrf_id: 63031
    vlan_id: 3031
    vrf_template: Default_VRF_Universal
    vrf_extension_template: Default_VRF_Extension_Universal
    service_vrf_template: null
    attach:
    - ip_address: "{{ devices.leaf_5.ip }}"
    - ip_address: "{{ devices.leaf_6.ip }}"
    - ip_address: "{{ devices.leaf_7.ip }}"
    - ip_address: "{{ devices.leaf_8.ip }}"

  f2_v2:
    name: f2_v2
    fabric: "{{ switch_fabrics.f2.name }}"
    vrf_name: v2
    vrf_id: 63032
    vlan_id: 3032
    vrf_template: Default_VRF_Universal
    vrf_extension_template: Default_VRF_Extension_Universal
    service_vrf_template: null
    attach:
    - ip_address: "{{ devices.leaf_5.ip }}"
    - ip_address: "{{ devices.leaf_6.ip }}"
    - ip_address: "{{ devices.leaf_7.ip }}"
    - ip_address: "{{ devices.leaf_8.ip }}"

### If using an MSD fabric to interconnect sites, we need to apply networks and
### VRFs to the MSD fabric, rather than the individual site fabrics.  The
### VRFs below are duplicates of the above site/switch fabric VRFs but additionally define
### attachments for the border_gateway roles, and will be used if the fabric name
### is an MSD fabric.

  msd_v1:
    name: msd_v1
    fabric: "{{ msd_fabrics.MSD.name }}"
    vrf_name: v1
    vrf_id: 63031
    vlan_id: 3031
    vrf_template: Default_VRF_Universal
    vrf_extension_template: Default_VRF_Extension_Universal
    service_vrf_template: null
    attach:
    - ip_address: "{{ devices.leaf_1.ip }}"
    - ip_address: "{{ devices.leaf_2.ip }}"
    - ip_address: "{{ devices.leaf_3.ip }}"
    - ip_address: "{{ devices.leaf_4.ip }}"
    - ip_address: "{{ devices.leaf_5.ip }}"
    - ip_address: "{{ devices.leaf_6.ip }}"
    - ip_address: "{{ devices.leaf_7.ip }}"
    - ip_address: "{{ devices.leaf_8.ip }}"
    - ip_address: "{{ devices.border_gateway_1.ip }}"
    - ip_address: "{{ devices.border_gateway_2.ip }}"
    - ip_address: "{{ devices.border_gateway_3.ip }}"
    - ip_address: "{{ devices.border_gateway_4.ip }}"

  msd_v2:
    name: msd_v2
    fabric: "{{ msd_fabrics.MSD.name }}"
    vrf_name: v2
    vrf_id: 63032
    vlan_id: 3032
    vrf_template: Default_VRF_Universal
    vrf_extension_template: Default_VRF_Extension_Universal
    service_vrf_template: null
    attach:
    - ip_address: "{{ devices.leaf_1.ip }}"
    - ip_address: "{{ devices.leaf_2.ip }}"
    - ip_address: "{{ devices.leaf_3.ip }}"
    - ip_address: "{{ devices.leaf_4.ip }}"
    - ip_address: "{{ devices.leaf_5.ip }}"
    - ip_address: "{{ devices.leaf_6.ip }}"
    - ip_address: "{{ devices.leaf_7.ip }}"
    - ip_address: "{{ devices.leaf_8.ip }}"
    - ip_address: "{{ devices.border_gateway_1.ip }}"
    - ip_address: "{{ devices.border_gateway_2.ip }}"
    - ip_address: "{{ devices.border_gateway_3.ip }}"
    - ip_address: "{{ devices.border_gateway_4.ip }}"
