# ndfc_policy_query_generated_config_all/main.yml
---
- name: main query FABRIC {{ fabric_name }} Generated Configs leaf
  include_tasks: worker.yml
  loop: "{{ leafs | json_query(mq1) }}"
  vars:
    mq1: "[?fabric == '{{ fabric_name }}']"

- name: main query FABRIC {{ fabric_name }} Generated Configs spine
  include_tasks: worker.yml
  loop: "{{ spines | json_query(mq2) }}"
  vars:
    mq2: "[?fabric == '{{ fabric_name }}']"

- name: main query FABRIC {{ fabric_name }} Generated Configs border_gateway
  include_tasks: worker.yml
  loop: "{{ border_gateways | json_query(mq3) }}"
  vars:
    mq3: "[?fabric == '{{ fabric_name }}']"

