# ndfc_policy_query_generated_config_all/main.yml
---
- name: main query generated config
  include_tasks: worker.yml
  loop: "{{ lookup('ansible.builtin.dict', devices) }}"
  when: "fabric_name in device.value.switch_fabric"
  loop_control:
    loop_var: device
