# ndfc_policy_query_generated_config_all/worker.yml
- name: worker query FABRIC {{ fabric_name }} DEVICE {{ item.name }} IP {{ item.ip }} generated_config 
  cisco.dcnm.dcnm_policy:
    fabric: "{{ fabric_name }}"
    state: query
    config:
      - switch:
          - ip: "{{ item.ip }}"
  register: wr1

- name: worker set_fact DEVICE {{ item.name }} IP {{ item.ip }}
  set_fact:
     generated_configs: "{{ wr1.response | json_query(wq1) }}"
  vars:
    wq1: "[?generatedConfig != ''].{TemplateName: templateName GeneratedConfig: generatedConfig}"
- name: show populated generated_configs {{ item.role}} {{ item.name }} {{ item.ip }}
  debug:
    var: generated_configs
