# ndfc_device_serial_number_get/tasks/worker.yml
- name: worker device_serial_number_get FABRIC {{ device.fabric }} NAME {{ device.name }} IP {{ device.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ device.fabric }}"
    state: query
    config:
    - seed_ip: "{{ device.ip }}"
  register: wr1

# Device serial number
- name: worker set_fact device_serial_number
  set_fact:
    device_serial_number: "{{ wr1.response | json_query(wq2) }}"
  vars:
    wq2: "[0].serialNumber"
