# ndfc_device_query/tasks/worker.yml
- name: worker query FABRIC {{ item.fabric }} NAME {{ item.name }} IP {{ item.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: query
    config:
    - seed_ip: "{{ item.ip }}"
  register: wr1

# playbooks can cull information from device_info
- name: worker set_fact device_info
  set_fact:
    device_info: "{{ wr1.response | json_query(wq1) }}"
  vars:
    wq1: "[0]"

# Device serial number
- name: worker set_fact serial
  set_fact:
    serial: "{{ wr1.response | json_query(wq2) }}"
  vars:
    wq2: "[0].serialNumber"
