# ndfc_device_query/tasks/worker.yml
- name: worker query FABRIC {{ item.fabric }} NAME {{ item.name }} IP {{ item.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: query
    config:
    - seed_ip: "{{ item.ip }}"
  register: result

# playbooks can cull information from device_info
- name: worker set_fact device_info
  set_fact:
    device_info: "{{ result.response | json_query(q2) }}"
  vars:
    q2: "[0]"

# used in playbooks to skip the query if serial is not defined
- name: worker set_fact serial
  set_fact:
    serial: "{{ result.response | json_query(q3) }}"
  vars:
    q3: "[0].serialNumber"
