# roles/ndfc_fabric_active_fabrics_get/tasks/main.yml
---
- name: main REST GET fabrics
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics"
  register: mr1
  vars:
    ansible_connection: httpapi
    ansible_httpapi_use_ssl: 'yes'
    ansible_httpapi_validate_certs: 'no'
    ansible_httpapi_port: 443

- name: main set_fact active_fabrics 
  set_fact:
     active_fabrics: "{{ mr1.response.DATA | json_query(mq1) | to_json }}"
  vars:
    mq1: "[*].{FabricName: fabricName}"
