# ndfc_rest_fabric_lan_classic_create/tasks/main.yml
---
- name: set_fact all_fabrics
  ansible.builtin.set_fact:
     all_fabrics: "{{ msd_fabrics | combine(switch_fabrics, external_fabrics, lan_classic_fabrics) }}"

- ansible.builtin.include_role:
    name: ndfc_rest_fabric_active_fabrics_get

- name: main set_fact FABRIC {{ fabric_name }}
  set_fact:
     LOOPBACK0_IP_RANGE: "{{ all_fabrics.values() | list | json_query(mq1) }}"
     IS_READ_ONLY: "{{ all_fabrics.values() | list | json_query(mq2) }}"
  vars:
    mq1: "[?name == '{{ fabric_name }}'].LOOPBACK0_IP_RANGE | [0]"
    mq2: "[?name == '{{ fabric_name }}'].IS_READ_ONLY | [0]"

- name: main REST POST LAN_Classic FABRIC {{ fabric_name }} ACTIVE_FABRICS {{ active_fabrics }}
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/LAN_Classic"
    json_data: "{{ vars_dict | to_json }}"
  when: "fabric_name not in active_fabrics"
  vars:
    ansible_connection: httpapi
    vars_dict:
      FABRIC_TECHNOLOGY: "LANClassic"
      FABRIC_TYPE: "External"
      FF: "LANClassic"
      LOOPBACK0_IP_RANGE: "{{ LOOPBACK0_IP_RANGE }}"
      IS_READ_ONLY: "{{ IS_READ_ONLY }}"
