# ndfc_device_merged_all/tasks/worker.yml

- ansible.builtin.include_role:
    name: ndfc_device_serial_number_get
  vars:
    device_name: "{{ item.name }}"
    fabric_name: "{{ item.fabric }}"

- name: worker merged FABRIC {{ item.fabric }} NAME {{ item.name }} device_serial_number {{ device_serial_number }} IP {{ item.ip }} MAX_HOPS {{ max_hops }} AUTH_PROTO {{ auth_proto }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: merged
    config:
    - seed_ip: "{{ item.ip }}"
      auth_proto: "{{ auth_proto }}"
      user_name: "{{ device_username }}"
      password: "{{ device_password }}"
      max_hops: "{{ max_hops }}"
      role: "{{ item.role }}"
      preserve_config: "{{ preserve_config }}" 
  when: "device_serial_number == ''"
