# ndfc_device_merged_all/tasks/worker.yml

- name: worker merged FABRIC {{ device.value.switch_fabric }} NAME {{ device.value.name }} IP {{ device.value.ip }} MAX_HOPS {{ max_hops }} AUTH_PROTO {{ auth_proto }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ device.value.switch_fabric }}"
    state: merged
    config:
    - seed_ip: "{{ device.value.ip }}"
      auth_proto: "{{ auth_proto }}"
      user_name: "{{ device_username }}"
      password: "{{ device_password }}"
      max_hops: "{{ max_hops }}"
      role: "{{ device.value.role }}"
      preserve_config: "{{ preserve_config }}" 
  vars:
    ansible_connection: httpapi

- ansible.builtin.include_role:
    name: ndfc_rest_config_deploy
  vars:
    fabric: "{{ device.value.switch_fabric }}"
    device_name: "{{ device.value.name }}"
