# ndfc_device_merged_all/tasks/worker.yml
- name: "query {{ item.fabric }} {{ item.name }} {{ item.ip }}"
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: query
    config:
    - seed_ip: "{{ item.ip }}"
  register: result

# Use serialNumber to determine if device already exists
- name: set_fact device serial number
  set_fact:
    serial: "{{ result.response | json_query(q2) }}"
  vars:
    q2: "[0].serialNumber"

- name: "merged {{ fabric_name }} {{ item.name }} serial ({{ serial }})"
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: merged
    config:
    - seed_ip: "{{ item.ip }}"
      auth_proto: "{{ auth_proto }}"
      user_name: "{{ device_username }}"
      password: "{{ device_password }}"
      max_hops: "{{ max_hops }}"
      role: "{{ item.role }}"
      preserve_config: "{{ preserve_config }}" 
  when: "serial == ''"
