# ndfc_device_merged/tasks/main.yml

- ansible.builtin.include_role:
    name: ndfc_device_config_get

- name: debug device_config.preserve_config
  ansible.builtin.debug:
    msg: "device_config.preserve_config {{ device_config.preserve_config }}"

- name: merged FABRIC {{ device_config.switch_fabric }} NAME {{ device_config.name }} IP {{ device_config.ip }} {{ device_config.preserve_config }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ device_config.switch_fabric }}"
    state: merged
    config:
    - seed_ip: "{{ device_config.ip }}"
      auth_proto: "{{ auth_proto }}"
      user_name: "{{ device_username }}"
      password: "{{ device_password }}"
      max_hops: "{{ max_hops }}"
      role: "{{ device_config.role }}"
      preserve_config: "{{ device_config.preserve_config }}"
  vars:
    ansible_connection: httpapi

- ansible.builtin.include_role:
    name: ndfc_rest_config_deploy
  vars:
    device_name: "{{ device_config.name }}"
