# ndfc_device_merged/tasks/worker.yml

- ansible.builtin.include_role:
    name: ndfc_device_config_get

- name: merged FABRIC {{ device_config.switch_fabric }} NAME {{ device_config.name }} IP {{ device_config.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ device_config.switch_fabric }}"
    state: merged
    config:
    - seed_ip: "{{ device_config.ip }}"
      auth_proto: "{{ auth_proto }}"
      user_name: "{{ device_username }}"
      password: "{{ device_password }}"
      max_hops: "{{ max_hops }}"
      role: "{{ device_config.role }}"
      preserve_config: "{{ preserve_config }}"

- ansible.builtin.include_role:
    name: ndfc_rest_config_deploy
  vars:
    device_name: "{{ device_config.name }}"
    fabric_name: "{{ device_config.switch_fabric }}"
