# ndfc_device_merged/tasks/main.yml
---
- name: ndfc_device_merged
  include_tasks: worker.yml
  loop: "{{ r1 }}"
  vars:
    q1: "[?name == '{{ device_name }}'] | [?fabric == '{{ fabric_name }}']"
    r1: "{{ leafs | json_query(q1) + spines | json_query(q1) + border_gateways | json_query(q1) }}"
