# ndfc_device_merged/tasks/worker.yml

- name: worker merged FABRIC {{ item.fabric }} NAME {{ item.name }} IP {{ item.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: merged
    config:
    - seed_ip: "{{ item.ip }}"
      auth_proto: "{{ auth_proto }}"
      user_name: "{{ device_username }}"
      password: "{{ device_password }}"
      max_hops: "{{ max_hops }}"
      role: "{{ item.role }}"
      preserve_config: "{{ preserve_config }}"

- ansible.builtin.include_role:
    name: ndfc_rest_config_deploy
  vars:
    device_name: "{{ item.name }}"
    fabric_name: "{{ item.fabric }}"
