# ndfc_device_merged/tasks/worker.yml
- name: worker query FABRIC {{ item.fabric }} NAME {{ item.name }} IP {{ item.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: query
    config:
    - seed_ip: "{{ item.ip }}"
  register: result

# serial is used below to skip device creation if the
# device already exists
- name: worker set_fact device serial number
  set_fact:
    serial: "{{ result.response | json_query(q2) }}"
  vars:
    q2: "[0].serialNumber"

- name: worker merged FABRIC {{ item.fabric }} NAME {{ item.name }} IP {{ item.ip }} SERIAL ({{ serial }})
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: merged
    config:
    - seed_ip: "{{ item.ip }}"
      auth_proto: "{{ auth_proto }}"
      user_name: "{{ device_username }}"
      password: "{{ device_password }}"
      max_hops: "{{ max_hops }}"
      role: "{{ item.role }}"
      preserve_config: "{{ preserve_config }}" 
  when: "serial == ''"
