# ndfc_fabric_delete_rest/tasks/main.yml
---
- name: Retrieve list of fabrics
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics"
  register: result
- name: set_fact active_fabrics 
  set_fact:
     active_fabrics: "{{ result.response.DATA | json_query(query) | to_json }}"
  vars:
    query: "[*].{FabricName: fabricName}"
- name: set_fact asn
  set_fact:
     asn: "{{ fabrics | json_query(query) }}"
  vars:
    query: "[?name == '{{ fabric_name }}'].asn | [0]"

- name: Fabric DELETE {{ fabric_name }} from ACTIVE_FABRICS {{ active_fabrics }}
  cisco.dcnm.dcnm_rest:
    method: DELETE
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}"
  when: "fabric_name in active_fabrics"
