# roles/ndfc_fabric_config_get/tasks/main.yml
---
- name: set_fact all_fabrics
  ansible.builtin.set_fact:
     all_fabrics: "{{ msd | combine(easy_fabric, external, lan_classic) }}"

- name: set_fact fabric_config {{ fabric_name }}
  ansible.builtin.set_fact:
     fabric_config: "{{ all_fabrics | json_query(mq1) }}"
  vars:
    mq1: "{{ fabric_name }}"
