# ndfc_rest_fabric_create/tasks/main.yml
---
- ansible.builtin.include_role:
    name: ndfc_rest_fabric_active_fabrics
- name: main set_fact FABRIC {{ fabric_name }}
  set_fact:
     BGP_AS: "{{ fabrics | json_query(mq1) }}"
     ANYCAST_RP_IP_RANGE: "{{ fabrics | json_query(mq2) }}"
     LOOPBACK0_IP_RANGE: "{{ fabrics | json_query(mq3) }}"
     LOOPBACK1_IP_RANGE: "{{ fabrics | json_query(mq4) }}"
     SUBNET_RANGE: "{{ fabrics | json_query(mq5) }}"
     FABRIC_MTU: "{{ fabrics | json_query(mq6) }}"
     REPLICATION_MODE: "{{ fabrics | json_query(mq7) }}"
  vars:
    mq1: "[?name == '{{ fabric_name }}'].BGP_AS | [0]"
    mq2: "[?name == '{{ fabric_name }}'].ANYCAST_RP_IP_RANGE | [0]"
    mq3: "[?name == '{{ fabric_name }}'].LOOPBACK0_IP_RANGE | [0]"
    mq4: "[?name == '{{ fabric_name }}'].LOOPBACK1_IP_RANGE | [0]"
    mq5: "[?name == '{{ fabric_name }}'].SUBNET_RANGE | [0]"
    mq6: "[?name == '{{ fabric_name }}'].FABRIC_MTU | [0]"
    mq7: "[?name == '{{ fabric_name }}'].REPLICATION_MODE | [0]"

- name: main REST POST Easy_Fabric FABRIC {{ fabric_name }} BGP_AS {{ BGP_AS }} ACTIVE_FABRICS {{ active_fabrics }}
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/Easy_Fabric"
    json_data: "{{ vars_dict | to_json }}"
  when: "fabric_name not in active_fabrics"
  vars:
    vars_dict:
      BGP_AS: "{{ BGP_AS }}"
      ANYCAST_RP_IP_RANGE: "{{ ANYCAST_RP_IP_RANGE }}"
      LOOPBACK0_IP_RANGE: "{{ LOOPBACK0_IP_RANGE }}"
      LOOPBACK1_IP_RANGE: "{{ LOOPBACK1_IP_RANGE }}"
      SUBNET_RANGE: "{{ SUBNET_RANGE }}"
      FABRIC_MTU: "{{ FABRIC_MTU }}"
      REPLICATION_MODE: "{{ REPLICATION_MODE }}"
