# ndfc_device_deleted_all/tasks/main.yml
- name: main deleted FABRIC {{ fabric_name }} all devices
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ fabric_name }}"
    state: deleted
  vars:
    ansible_connection: httpapi
