# ndfc_vpc_delete/tasks/main.yml

# REST returns internal server error (500) when called from 
# Ansible dcnm_rest module per below.  Hence, this is a work in progress
# and doesn't work.

# Retrieve serial number and vpc config state for vpc_peer_1
- name: main query vpc_peer_1 {{ fabric_name }} {{ vpc_name }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ fabric_name }}"
    state: query
    config:
    - seed_ip: "{{ ip }}"
  register: mr1
  vars:
    mq1: "[?fabric == '{{ fabric_name }}'] | [?name == '{{ vpc_name }}'].peer_1_ip | [0]"
    ip: "{{ vpc_peers | json_query(mq1)}}"
- name: main set_fact vpc_peer_1 serial number
  set_fact:
    p1_serial: "{{ mr1.response | json_query(mq2) }}"
    p1_vpc: "{{ mr1.response | json_query(mq3) }}"
  vars:
    mq2: "[0].serialNumber"
    mq3: "[0].isVpcConfigured"

# Retrieve serial number and vpc config state for vpc_peer_2
- name: main query vpc_peer_2 {{ fabric_name }} {{ vpc_name }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ fabric_name }}"
    state: query
    config:
    - seed_ip: "{{ ip }}"
  register: mr2
  vars:
    mq4: "[?fabric == '{{ fabric_name }}'] | [?name == '{{ vpc_name }}'].peer_2_ip | [0]"
    ip: "{{ vpc_peers | json_query(mq4)}}"

- name: main set_fact vpc_peer_2 serial number
  set_fact:
    p2_serial: "{{ mr2.response | json_query(mq5) }}"
    p2_vpc: "{{ mr2.response | json_query(mq6) }}"
  vars:
    mq5: "[0].serialNumber"
    mq6: "[0].isVpcConfigured"

# Conditionally delete vpc peering
- name: main REST DELETE VPC Peers fabric_name {{ fabric_name }} vpc_name {{ vpc_name }} configured {{ p1_vpc }}/{{ p2_vpc }} serial_numbers {{ p1_serial }}/{{ p2_serial }}"
  cisco.dcnm.dcnm_rest:
    method: DELETE
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/vpcpair"
    json_data: "{{ vars_dict | to_json }}"
  vars:
    vars_dict:
      serialNumber: "{{ p2_serial }}"
  when: p1_serial != '' and p2_serial != '' and p1_vpc == True and p2_vpc == True
