---
- name: worker query FABRIC {{ item.fabric }} NETWORK {{ item.net_name }}
  cisco.dcnm.dcnm_network:
    fabric: "{{ fabric_name }}"
    state: query
    config:
    - net_name: "{{ item.net_name }}"
  register: wr1
  # when: "item.net_name is not none"

- name: worker set_fact network_info
  set_fact:
    network_info: "{{ wr1.response | json_query(wq1) | default('', true) }}"
  vars:
    wq1: "[0].parent"
  # when: "item.net_name is not none"

# - name: worker set_fact network_info null
#   set_fact:
#     network_info: "{{ wr1.response | json_query(wq1) }}"
#   vars:
#     wq1: "[0].parent"
#   when: "item.net_name is none"
