# ndfc_rest_fabric_info_get/tasks/main.yml
---
- ansible.builtin.include_role:
    name: ndfc_rest_fabric_active_fabrics_get

- name: main REST POST FABRIC {{ fabric_name }} active_fabrics {{ active_fabrics }}
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{fabric_name}}"
  when: "fabric_name in active_fabrics"
  register: mr1
  vars:
    ansible_connection: httpapi

- name: set_fact fabric_info
  ansible.builtin.set_fact:
    fabric_info: "{{ mr1 }}"
  when: "fabric_name in active_fabrics"

- name: set_fact fabric_info null
  ansible.builtin.set_fact:
    fabric_info: ""
  when: "fabric_name not in active_fabrics"
