# ndfc_rest_fabric_asn_get
# Returns the current fabric asn in var 'fabric_asn'
# if fabric exists, fabric_asn will contain the fabric's BGP ASN
# if fabric does not exist, fabric_asn will be null
---
- ansible.builtin.include_role:
    name: ndfc_rest_fabric_active_fabrics_get

- name: get fabric info fabric {{ fabric_name }}
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}"
  register: mr1
  when: fabric_name in active_fabrics
  vars:
    ansible_connection: httpapi

- name: "main set_fact fabric_asn {{ mr1.response.DATA.asn }} if fabric exists"
  set_fact:
    fabric_asn: "{{ mr1.response.DATA.asn }}"
  when: fabric_name in active_fabrics

- name: main set_fact fabric_asn null if fabric does not exist)
  set_fact:
    fabric_asn: null
  when: fabric_name not in active_fabrics
