---
- ansible.builtin.include_role:
    name: ndfc_network_info_get
  vars:
    fabric_name: "{{ dn.fabric }}"
    network_name: "{{ dn.net_name }}"

# We set wf1 to '' so that we can skip the last task below if it's still equal to ''
- name: set fact wf1 temp
  set_fact:
    wf1: ''

- name: worker set_fact wf1 networkName
  set_fact:
    wf1: "{{ network_info | json_query(wq1) | default('', true) }}"
  vars:
    wq1: "networkName"
  when: "network_info != ''"

- name: worker deleted FABRIC {{ dn.fabric }} NETWORK {{ dn.net_name }} networkName ({{ wf1 }})
  cisco.dcnm.dcnm_network:
    fabric: "{{ dn.fabric }}"
    state: deleted
    config:
    - net_name: "{{ dn.net_name }}"
  when: "wf1 == network_name"
