# ndfc_vrf_replaced/tasks/main.yml
---
- name: main query FABRIC {{ fabric_name }} VRF {{ vrf_name }}
  include_tasks: worker.yml
  loop: "{{ mr1 }}"
  vars:
    mq1: "[?fabric == '{{ fabric_name }}'] | [?vrf_name == '{{ vrf_name }}']"
    mr1: "{{ vrfs | json_query(mq1) }}"
