# ndfc_vrf_query/tasks/worker.yml
---
- ansible.builtin.include_role:
    name: ndfc_vrf_config_get

- name: worker query FABRIC {{ vrf_config.fabric }} VRF {{ vrf_config.vrf_name }}
  cisco.dcnm.dcnm_vrf:
    fabric: "{{ vrf_config.fabric }}"
    state: query
    config:
    - vrf_name: "{{ vrf_config.vrf_name }}"
  register: mr1
  vars:
    ansible_connection: httpapi

# playbooks can cull information from the vrf_info object
- name: set_fact info
  set_fact:
    vrf_info: "{{ mr1.response[0] }}"

