# ndfc_vrf_query/tasks/worker.yml
- name: worker query FABRIC {{ item.fabric }} VRF {{ item.vrf_name }}
  cisco.dcnm.dcnm_vrf:
    fabric: "{{ item.fabric }}"
    state: query
    config:
    - vrf_name: "{{ item.vrf_name }}"
  register: mr1

# playbooks can cull information from the info object
- name: set_fact info
  set_fact:
    info: "{{ mr1.response[0] }}"
