# ndfc_rest_device_list_by_fabric/tasks/main.yml
#
# Return JSON object 'info' which will be a list of switch dictionaries
# if the GET request is successful, or an empty list if the GET request fails
---
- name: main REST GET FABRIC {{ fabric_name }} switchesByFabric
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/inventory/switchesByFabric"
  register: result
  ignore_errors: true
- name: main set_fact info SUCCESS
  set_fact:
     info: "{{ result.response.DATA }}"
  when:
    result is succeeded
- name: main set_fact info FAILED
  set_fact:
     info: "{{ [] | to_json }}"
  when:
    result is failed
