# ndfc_device_query_all/tasks/main.yml
---
- name: main query FABRIC {{ fabric_name }}
  include_tasks: worker.yml
  loop: "{{ r1 }}"
  vars:
    q1: "[?fabric == '{{ fabric_name }}']"
    r1: "{{ leafs | json_query(q1) + spines | json_query(q1) + border_gateways | json_query(q1) }}"
