# ndfc_device_query_all/tasks/worker.yml
- name: worker query FABRIC {{ item.fabric }} NAME {{ item.name }} IP {{ item.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: query
    config:
    - seed_ip: "{{ item.ip }}"
  register: result

- name: worker set_fact serial
  set_fact:
    serial: "{{ result.response | json_query(q2) }}"
  vars:
    q2: "[0].serialNumber"

- debug:
    msg: "uptime: {{ result.response[0].upTime }} - {{ item.fabric }} {{ item.name }} {{ item.ip }}"
  when: "serial != ''"
- debug:
    msg: "serial: {{ result.response[0].serialNumber }} - {{ item.fabric }} {{ item.name }} {{ item.ip }}"
  when: "serial != ''"
- debug:
    msg: "version: {{ result.response[0].release }} - {{ item.fabric }} {{ item.name }} {{ item.ip }}"
  when: "serial != ''"
