# ndfc_device_query_all/tasks/worker.yml
- name: worker query FABRIC {{ item.fabric }} NAME {{ item.name }} IP {{ item.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ item.fabric }}"
    state: query
    config:
    - seed_ip: "{{ item.ip }}"
  register: wr1

- name: worker set_fact serial
  set_fact:
    serial: "{{ wr1.response | json_query(wq1) }}"
  vars:
    wq1: "[0].serialNumber"

- debug:
    msg: "uptime: {{ wr1.response[0].upTime }} - {{ item.fabric }} {{ item.name }} {{ item.ip }}"
  when: "serial != ''"
- debug:
    msg: "serial: {{ wr1.response[0].serialNumber }} - {{ item.fabric }} {{ item.name }} {{ item.ip }}"
  when: "serial != ''"
- debug:
    msg: "version: {{ wr1.response[0].release }} - {{ item.fabric }} {{ item.name }} {{ item.ip }}"
  when: "serial != ''"
