# ndfc_device_ipv4_address_local_get/tasks/worker.yml

- ansible.builtin.include_role:
    name: ndfc_device_config_get

# Device ipv4 address
- name: worker set_fact device_ipv4_address
  set_fact:
    device_ipv4_address: "{{ device_config.ip }}"
