# ndfc_rest_fabric_external_create/tasks/main.yml
---
- ansible.builtin.include_role:
    name: ndfc_rest_fabric_active_fabrics

# TODO: add relevant user-configurable parameters to common_vars and update the
# below accordingly.
- name: main set_fact external_fabric {{ fabric_name }}
  set_fact:
     BGP_AS: "{{ external_fabrics | json_query(mq1) }}"
     DCI_SUBNET_RANGE: "{{ external_fabrics | json_query(mq2) }}"
     DCI_SUBNET_TARGET_MASK: "{{ external_fabrics | json_query(mq3) }}"
     IS_READ_ONLY: "{{ external_fabrics | json_query(mq4) }}"
     LOOPBACK0_IP_RANGE: "{{ external_fabrics | json_query(mq5) }}"
     POWER_REDUNDANCY_MODE: "{{ external_fabrics | json_query(mq6) }}"
     SUBINTERFACE_RANGE: "{{ external_fabrics | json_query(mq7) }}"
  vars:
    mq1: "[?name == '{{ fabric_name }}'].BGP_AS | [0]"
    mq2: "[?name == '{{ fabric_name }}'].DCI_SUBNET_RANGE | [0]"
    mq3: "[?name == '{{ fabric_name }}'].DCI_SUBNET_TARGET_MASK | [0]"
    mq4: "[?name == '{{ fabric_name }}'].IS_READ_ONLY | [0]"
    mq5: "[?name == '{{ fabric_name }}'].LOOPBACK0_IP_RANGE | [0]"
    mq6: "[?name == '{{ fabric_name }}'].POWER_REDUNDANCY_MODE | [0]"
    mq7: "[?name == '{{ fabric_name }}'].SUBINTERFACE_RANGE | [0]"


- name: main REST POST external_fabric {{ fabric_name }} active_fabrics {{ active_fabrics }}
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/"
    json_data: "{{ vars_dict | to_json }}"
  when: "fabric_name not in active_fabrics"
  vars:
    vars_dict:
      fabricName: "{{ fabric_name }}"
      templateName: "External_Fabric"
      nvPairs:
        AAA_REMOTE_IP_ENABLED: false
        AAA_SERVER_CONF: ""
        BGP_AS: "{{ BGP_AS }}"
        BOOTSTRAP_CONF: ""
        BOOTSTRAP_ENABLE: false
        BOOTSTRAP_MULTISUBNET: ""
        BOOTSTRAP_MULTISUBNET_INTERNAL: ""
        CDP_ENABLE: false
        DCI_SUBNET_RANGE: "{{ DCI_SUBNET_RANGE }}"
        DCI_SUBNET_TARGET_MASK: "{{ DCI_SUBNET_TARGET_MASK }}"
        DEPLOYMENT_FREEZE: false
        DHCP_ENABLE: false
        DHCP_END: ""
        DHCP_END_INTERNAL: ""
        DHCP_IPV6_ENABLE: ""
        DHCP_IPV6_ENABLE_INTERNAL: ""
        DHCP_START: ""
        DHCP_START_INTERNAL: ""
        enableRealTimeBackup: ""
        enableScheduledBackup: ""
        ENABLE_AAA: false
        ENABLE_NETFLOW: false
        ENABLE_NETFLOW_PREV: ""
        ENABLE_NXAPI: false
        ENABLE_NXAPI_HTTP: false
        FABRIC_FREEFORM: ""
        FABRIC_NAME: "{{ fabric_name }}"
        FABRIC_TYPE: External
        FEATURE_PTP: false
        FEATURE_PTP_INTERNAL: false
        FF: External
        INBAND_ENABLE: false
        INBAND_ENABLE_PREV: false
        INBAND_MGMT: false
        INBAND_MGMT_PREV: false
        IS_READ_ONLY: "{{ IS_READ_ONLY }}"
        LOOPBACK0_IP_RANGE: "{{ LOOPBACK0_IP_RANGE }}"
        MGMT_GW: ""
        MGMT_GW_INTERNAL: ""
        MGMT_PREFIX: ""
        MGMT_PREFIX_INTERNAL: ""
        MGMT_V6PREFIX: "64"
        MGMT_V6PREFIX_INTERNAL: ""
        MPLS_HANDOFF: false
        MPLS_LB_ID: ""
        MPLS_LOOPBACK_IP_RANGE: ""
        MSO_CONNECTIVITY_DEPLOYED: ""
        MSO_CONTROLER_ID: ""
        MSO_SITE_GROUP_NAME: ""
        MSO_SITE_ID: ""
        NETFLOW_EXPORTER_LIST: ""
        NETFLOW_MONITOR_LIST: ""
        NETFLOW_RECORD_LIST: ""
        PM_ENABLE: false
        PM_ENABLE_PREV: false
        POWER_REDUNDANCY_MODE: "{{ POWER_REDUNDANCY_MODE }}"
        PREMSO_PARENT_FABRIC: ""
        PTP_DOMAIN_ID: ""
        PTP_LB_ID: ""
        scheduledTime: ""
        SNMP_SERVER_HOST_TRAP: true
        SUBINTERFACE_RANGE: "{{ SUBINTERFACE_RANGE }}"

