# ndfc_rest_interface_shutdown/tasks/main.yml
- ansible.builtin.include_role:
    name: ndfc_device_config_get

- name: query FABRIC {{ device_config.switch_fabric }} NAME {{ device_config.name }} IP {{ device_config.ip }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ device_config.switch_fabric }}"
    state: query
    config:
    - seed_ip: "{{ device_config.ip }}"
  register: wr1

- ansible.builtin.include_role:
    name: ndfc_device_serial_number_get

- name: REST POST interface shutdown FABRIC {{ device_config.switch_fabric }} NAME {{ device_config.name }} IP {{ device_config.ip }} SERIAL {{ device_serial_number }} INTERFACE {{ interface_name }} payload {{ payload }}
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/interface/adminstatus"
    json_data: "{{ payload | to_json }}"
  when: "device_serial_number != ''"
  vars:
    ansible_connection: httpapi
    payload:
      operation: "shut"
      interfaces:
      - serialNumber: "{{ device_serial_number }}"
        ifName: "{{ interface_name }}"

- ansible.builtin.include_role:
    name: ndfc_rest_config_deploy
  vars:
    device_name: "{{ device_config.name }}"
  when: "device_serial_number != ''"
