# ndfc_policy_query_interface/tasks/main.yml
---
- name: main query FABRIC {{ fabric_name }} Interface Policies leaf
  include_tasks: worker.yml
  loop: "{{ leafs | json_query(qm1) }}"
  vars:
    qm1: "[?fabric == '{{ fabric_name }}']"

- name: main query FABRIC {{ fabric_name }} Interface Policies spine
  include_tasks: worker.yml
  loop: "{{ spines | json_query(qm2) }}"
  vars:
    qm2: "[?fabric == '{{ fabric_name }}']"

- name: main query FABRIC {{ fabric_name }} Interface Policies border_gateway
  include_tasks: worker.yml
  loop: "{{ border_gateways | json_query(qm3) }}"
  vars:
    qm3: "[?fabric == '{{ fabric_name }}']"
