# ndfc_policy_query_interface/tasks/worker.yml
- name: worker query FABRIC {{ fabric_name }} ROLE {{ item.role}} DEVICE {{ item.name }} INTERFACE {{ interface_name }}"
  cisco.dcnm.dcnm_policy:
    fabric: "{{ fabric_name }}"
    state: query
    config:
      - switch:
          - ip: "{{ item.ip }}"
  register: wr1

- name: worker set_fact interface_config
  set_fact:
     interface_config: "{{ wr1.response | json_query(wq1) }}"
  vars:
    wq1: "[?contains(generatedConfig, '{{ interface_name }}') == `true`].{TemplateName: templateName GeneratedConfig: generatedConfig}"

- name: worker show interface policy INTERFACE {{ interface_name }}
  debug:
    var: interface_config
