# ndfc_service_route_peering_config_get/tasks/main.yml
---
- name: set_fact service_route_peering_config {{ service_route_peering_name }}
  ansible.builtin.set_fact:
     service_route_peering_config: "{{ service_route_peerings | json_query(service_route_peering_config_q1) }}"
  vars:
    service_route_peering_config_q1: "{{ service_route_peering_name }}"
