# ndfc_config_deploy_all_rest/tasks/main.yml
---
- cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/config-save"
    json_data: "{{ vars_dict | to_json }}"
  vars:
    vars_dict:
      forceShowRun: "{{ forceShowRun }}"
      inclAllMSDSwitches: "{{ inclAllMSDSwitches }}"
- cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/config-deploy"
    json_data: "{{ vars_dict | to_json }}"
  vars:
    vars_dict:
      forceShowRun: "{{ forceShowRun }}"
      inclAllMSDSwitches: "{{ inclAllMSDSwitches }}"