# ndfc_device_list_by_fabric_rest/tasks/main.yml
#
# Return JSON object 'info' which will be a list of switch dictionaries
# if the GET request is successful, or an empty list if the GET request fails
---
- name: Retrieve list of devices in fabric {{ fabric_name }}
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/inventory/switchesByFabric"
  register: result
  ignore_errors: true
- name: set_fact info on success
  set_fact:
     info: "{{ result.response.DATA }}"
  when:
    result is succeeded
- name: set_fact info on failed
  set_fact:
     info: "{{ [] | to_json }}"
  when:
    result is failed
